### ISSUE TITLE
About RFRNet code

### ISSUE THREAD

**Issue by yabg-shuai666** [jingyuanli001/RFR-Inpainting#4]
for i in range(6):
            x2, m2 = self.Pconv21(x2, m2)
            x2, m2 = self.Pconv22(x2, m2)
            x2 = F.leaky_relu(self.bn2(x2), inplace = True)
            x2 = self.RFRModule(x2, m2[:,0:1,:,:])
            x2 = x2 * m2
About RFRNet code , I wonder why the result x2 after self.RFRModule needs to be carried out x2 = x2 * m2。This will obscure the newly generated pixels。Looking forward to your reply，thank you.

**Comment by jingyuanli001** [comment]
Thanks for your question. 
This part is an intentional design in RFRNet. The basic idea behind the RFRNet is that when there are a large number of missing pixels, the contents in the known region is not informative for recovering the pixels in the hole center. As a consequence, in the earlier iterations during inpainting, we drop the synthesized pixels in the hole center and recover these pixels in later iterations when there are more known pixels. In x2 = x2 * m2, the m2 is an updated mask whose hole region is smaller than that from the previous m2. This way, we can progressively inpaint the missing regions from their boundaries to the centers.
