### ISSUE TITLE
How can I change the code to fix images of other sizes? For example: 1024*768

### ISSUE THREAD

**Issue by caimaomao315** [jingyuanli001/RFR-Inpainting#59]

**Comment by 01SHENyankun** [comment]
你好，请问你复现了这个网络了吗，有点问题想请教，2635505974

**Comment by caimaomao315** [comment]
嗯嗯 什么问题&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 上午9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)





 
你好，请问你复现了这个网络了吗，有点问题想请教，2635505974
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 01SHENyankun** [comment]
我按着readme里的命令进行测试，发现运行不成功，想问问你，你在训练完成以后都进行了什么操作，微调？怎么进行测试啊

**Comment by caimaomao315** [comment]
进行微调和test的时候&nbsp; 分别加上default=True，然后训练的时候这份代码我记得是在别人模型基础上进行训练的'--model_path', type=str, default="pretrainedModel/g_640000.pth"&nbsp; 即先调用别人的模型 再训练


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 晚上9:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)





 
我按着readme里的命令进行测试，发现运行不成功，想问问你，你在训练完成以后都进行了什么操作，微调？怎么进行测试啊
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 01SHENyankun** [comment]
首先谢谢你的回复，这是我之前测试时的两个命令，但是都失败了，我需要在这基础之上加什么吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 晚上9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)





 进行微调和test的时候&amp;nbsp; 分别加上default=True，然后训练的时候这份代码我记得是在别人模型基础上进行训练的'--model_path', type=str, default="pretrainedModel/g_640000.pth"&amp;nbsp; 即先调用别人的模型 再训练 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月20日(星期六) 晚上9:23 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59) 
 
 
 
 
 
   
 我按着readme里的命令进行测试，发现运行不成功，想问问你，你在训练完成以后都进行了什么操作，微调？怎么进行测试啊 
   
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caimaomao315** [comment]
你哪两个命令？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 晚上9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)





 首先谢谢你的回复，这是我之前测试时的两个命令，但是都失败了，我需要在这基础之上加什么吗 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月20日(星期六) 晚上9:33 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59) 
 
 
 
 
 
  进行微调和test的时候&amp;amp;nbsp; 分别加上default=True，然后训练的时候这份代码我记得是在别人模型基础上进行训练的'--model_path', type=str, default="pretrainedModel/g_640000.pth"&amp;amp;nbsp; 即先调用别人的模型 再训练  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年11月20日(星期六) 晚上9:23  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)  
   
   
   
   
   
     
  我按着readme里的命令进行测试，发现运行不成功，想问问你，你在训练完成以后都进行了什么操作，微调？怎么进行测试啊  
     
  —  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 01SHENyankun** [comment]
&nbsp;python run.py --test

还有
&nbsp;python run.py --data_root D:/Datasets/celebA/img/img_align_celeba --mask_root D:/Datasets/masks/irregular_mask --model_path checkpoints/g_10000.pth --test --mask_mode 2





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 晚上9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)





 你哪两个命令？ 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月20日(星期六) 晚上9:40 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59) 
 
 
 
 
 
  首先谢谢你的回复，这是我之前测试时的两个命令，但是都失败了，我需要在这基础之上加什么吗  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年11月20日(星期六) 晚上9:33  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)  
   
   
   
   
   
   进行微调和test的时候&amp;amp;amp;nbsp; 分别加上default=True，然后训练的时候这份代码我记得是在别人模型基础上进行训练的'--model_path', type=str, default="pretrainedModel/g_640000.pth"&amp;amp;amp;nbsp; 即先调用别人的模型 再训练   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年11月20日(星期六) 晚上9:23   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)   
     
     
     
     
     
       
   我按着readme里的命令进行测试，发现运行不成功，想问问你，你在训练完成以后都进行了什么操作，微调？怎么进行测试啊   
       
   —   
   You are receiving this because you authored the thread.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caimaomao315** [comment]
从这看的话 是先训练出自己的模型 再进行test&nbsp; &nbsp;然后&nbsp; 路径那 使用相对路径&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 晚上9:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)





 &amp;nbsp;python run.py --test 
 
 还有 
 &amp;nbsp;python run.py --data_root D:/Datasets/celebA/img/img_align_celeba --mask_root D:/Datasets/masks/irregular_mask --model_path checkpoints/g_10000.pth --test --mask_mode 2 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月20日(星期六) 晚上9:47 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59) 
 
 
 
 
 
  你哪两个命令？  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年11月20日(星期六) 晚上9:40  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)  
   
   
   
   
   
   首先谢谢你的回复，这是我之前测试时的两个命令，但是都失败了，我需要在这基础之上加什么吗   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年11月20日(星期六) 晚上9:33   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)   
     
     
     
     
     
    进行微调和test的时候&amp;amp;amp;amp;nbsp; 分别加上default=True，然后训练的时候这份代码我记得是在别人模型基础上进行训练的'--model_path', type=str, default="pretrainedModel/g_640000.pth"&amp;amp;amp;amp;nbsp; 即先调用别人的模型 再训练    
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年11月20日(星期六) 晚上9:23    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)    
       
       
       
       
       
         
    我按着readme里的命令进行测试，发现运行不成功，想问问你，你在训练完成以后都进行了什么操作，微调？怎么进行测试啊    
         
    —    
    You are receiving this because you authored the thread.    
    Reply to this email directly, view it on GitHub, or unsubscribe.    
    Triage notifications on the go with GitHub Mobile for iOS or Android.    
   —   
   You are receiving this because you commented.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 01SHENyankun** [comment]
你好，咱们能加一个联系方式吗，我现在正在进行微调，估计明天就能完成，在向你请教


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 晚上9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)





 从这看的话 是先训练出自己的模型 再进行test&amp;nbsp; &amp;nbsp;然后&amp;nbsp; 路径那 使用相对路径&amp;nbsp; 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月20日(星期六) 晚上9:48 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59) 
 
 
 
 
 
  &amp;amp;nbsp;python run.py --test  
   
  还有  
  &amp;amp;nbsp;python run.py --data_root D:/Datasets/celebA/img/img_align_celeba --mask_root D:/Datasets/masks/irregular_mask --model_path checkpoints/g_10000.pth --test --mask_mode 2  
   
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年11月20日(星期六) 晚上9:47  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)  
   
   
   
   
   
   你哪两个命令？   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年11月20日(星期六) 晚上9:40   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)   
     
     
     
     
     
    首先谢谢你的回复，这是我之前测试时的两个命令，但是都失败了，我需要在这基础之上加什么吗    
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年11月20日(星期六) 晚上9:33    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)    
       
       
       
       
       
     进行微调和test的时候&amp;amp;amp;amp;amp;nbsp; 分别加上default=True，然后训练的时候这份代码我记得是在别人模型基础上进行训练的'--model_path', type=str, default="pretrainedModel/g_640000.pth"&amp;amp;amp;amp;amp;nbsp; 即先调用别人的模型 再训练     
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;amp;amp;amp;gt;;     
     发送时间:&amp;amp;amp;amp;amp;nbsp;2021年11月20日(星期六) 晚上9:23     
     ***@***.***&amp;amp;amp;amp;amp;gt;;     
     ***@***.******@***.***&amp;amp;amp;amp;amp;gt;;     
     主题:&amp;amp;amp;amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)     
         
         
         
         
         
           
     我按着readme里的命令进行测试，发现运行不成功，想问问你，你在训练完成以后都进行了什么操作，微调？怎么进行测试啊     
           
     —     
     You are receiving this because you authored the thread.     
     Reply to this email directly, view it on GitHub, or unsubscribe.     
     Triage notifications on the go with GitHub Mobile for iOS or Android.     
    —    
    You are receiving this because you commented.    
    Reply to this email directly, view it on GitHub, or unsubscribe.    
    Triage notifications on the go with GitHub Mobile for iOS or Android.    
   —   
   You are receiving this because you authored the thread.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caimaomao315** [comment]
1871823196




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 晚上9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)





 你好，咱们能加一个联系方式吗，我现在正在进行微调，估计明天就能完成，在向你请教 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月20日(星期六) 晚上9:55 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59) 
 
 
 
 
 
  从这看的话 是先训练出自己的模型 再进行test&amp;amp;nbsp; &amp;amp;nbsp;然后&amp;amp;nbsp; 路径那 使用相对路径&amp;amp;nbsp;  
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年11月20日(星期六) 晚上9:48  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)  
   
   
   
   
   
   &amp;amp;amp;nbsp;python run.py --test   
     
   还有   
   &amp;amp;amp;nbsp;python run.py --data_root D:/Datasets/celebA/img/img_align_celeba --mask_root D:/Datasets/masks/irregular_mask --model_path checkpoints/g_10000.pth --test --mask_mode 2   
     
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年11月20日(星期六) 晚上9:47   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)   
     
     
     
     
     
    你哪两个命令？    
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年11月20日(星期六) 晚上9:40    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)    
       
       
       
       
       
     首先谢谢你的回复，这是我之前测试时的两个命令，但是都失败了，我需要在这基础之上加什么吗     
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;amp;amp;amp;gt;;     
     发送时间:&amp;amp;amp;amp;amp;nbsp;2021年11月20日(星期六) 晚上9:33     
     ***@***.***&amp;amp;amp;amp;amp;gt;;     
     ***@***.******@***.***&amp;amp;amp;amp;amp;gt;;     
     主题:&amp;amp;amp;amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)     
         
         
         
         
         
      进行微调和test的时候&amp;amp;amp;amp;amp;amp;nbsp; 分别加上default=True，然后训练的时候这份代码我记得是在别人模型基础上进行训练的'--model_path', type=str, default="pretrainedModel/g_640000.pth"&amp;amp;amp;amp;amp;amp;nbsp; 即先调用别人的模型 再训练      
           
           
      ------------------&amp;amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;amp;nbsp;------------------      
      发件人:                                                                                                                        "jingyuanli001/RFR-Inpainting"                                                                                    ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      发送时间:&amp;amp;amp;amp;amp;amp;nbsp;2021年11月20日(星期六) 晚上9:23      
      ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      ***@***.******@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      主题:&amp;amp;amp;amp;amp;amp;nbsp;Re: [jingyuanli001/RFR-Inpainting] How can I change the code to fix images of other sizes? For example: 1024*768 (Issue #59)      
           
           
           
           
           
             
      我按着readme里的命令进行测试，发现运行不成功，想问问你，你在训练完成以后都进行了什么操作，微调？怎么进行测试啊      
             
      —      
      You are receiving this because you authored the thread.      
      Reply to this email directly, view it on GitHub, or unsubscribe.      
      Triage notifications on the go with GitHub Mobile for iOS or Android.      
     —     
     You are receiving this because you commented.     
     Reply to this email directly, view it on GitHub, or unsubscribe.     
     Triage notifications on the go with GitHub Mobile for iOS or Android.     
    —    
    You are receiving this because you authored the thread.    
    Reply to this email directly, view it on GitHub, or unsubscribe.    
    Triage notifications on the go with GitHub Mobile for iOS or Android.    
   —   
   You are receiving this because you commented.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShiKangdi** [comment]
> 你好，咱们能加一个联系方式吗，我现在正在进行微调，估计明天就能完成，在向你请教
> […](#)

你好，请问你在CelebA上训练的时候Crop了吗?
