### ISSUE TITLE
FP16 training.

### ISSUE THREAD

**Issue by ternaus** [jingyuanli001/RFR-Inpainting#8]
Trying to train the model using the fp16 setting, 

but the model outputs `-inf`'s during the forward pass.

**Comment by alexwitt2399** [comment]
I recommend changing [this](https://github.com/jingyuanli001/RFR-Inpainting/blob/159ac0857569040aac87564dcd6e6c3d3d741cf4/modules/partialconv2d.py#L57) and [this](https://github.com/jingyuanli001/RFR-Inpainting/blob/159ac0857569040aac87564dcd6e6c3d3d741cf4/modules/RFRNet.py#L169) line to a number within the range of fp16. Fixed the issue for me (using APEX)

**Comment by xiankgx** [comment]
@alexwitt2399 ,

Hi, how is your experience training with fp16? I made some changes to the code following your suggestions and I was able to train for quite a long time without NaN. However, NaN eventually still pop out due to multiple recurrence and partial conv. Setting epsilon to a higher number like 1e-4 still didn't help. Also, the output images is very "fish scale-ly" or having "studded patterns" when training with fp16. Changing to fp32 eventually solves most of those problems.
